### ISSUE TITLE
Not an issue but a curiosity - what ascii style is that in the xerolinux script?

### ISSUE THREAD

**Issue by CavaleriOmar** [xerolinux/xlapit-cli#1]
I am forking the script to fit my needs (studying coding in rust)... and I would like to keep the stylistic consistency of the ascii logo. What program is it done with?

**Comment by DarkXero-dev** [comment]
That's what #OpenSource is.. Enjoy it... As for ASCII we used that here 
[Symbols](https://fsymbols.com/generators/tarty/)
