### ISSUE TITLE
enable native compilation too

### ISSUE THREAD

**Issue by Martinligabue** [xerolinux/xlapit-cli#11]
in xero-scripts/scripts/tool_init.sh, in the multithread enabler, I'd change the default -march=x86-64 -mtune=generic to -march=native
The upside is a small improvement in the performance/size of the compiled packages (usually not by a lot), the downside is that the compiled packages can't usually run on different pcs, but I never saw anyone compile aur packages and expect them to work on other pcs, so maybe a warning might be needed, if you feel like it.
I tried making a pr, but failed with the sed regexp, lol.

**Comment by DarkXero-dev** [comment]
Thanks for the suggestion.

But I prefer to leave it as is for compatibility sake. At least for now. But in the future might update it. There is currently a debate around the native vs x86_64 architectures. Don't wanna add salt to a wound.

**Comment by Martinligabue** [comment]
thanks, makes sense

maybe there could be an advanced optimization menu, with more dangerous settings, that might not suit everyone, yet in some common cases are helpful

**Comment by DarkXero-dev** [comment]
Thanks for understanding. I will close it. Don't worry it's been on my mind for a while I won't forget. 

Cheers.
