### ISSUE TITLE
Scripts should run with set -eu.

### ISSUE THREAD

**Issue by it-a-me** [xerolinux/xlapit-cli#6]
`set -e` causes the script to exit when any command exits with a non-zero return code outside of an if statement and a few other cases. See `man 1p set` for details

`set -u` causes the script to exit with an error whenever it attempts to expand an empty variable. It prevents typos in variable names from failing silently.

**Comment by DarkXero-dev** [comment]
Will test n see if it doesn't break when user cancels out of the ncurses dialog.

**Comment by DarkXero-dev** [comment]
Nope doesn't work still breaks when user cancels out from an nCurses dialog page. So reverted.
